// Producer Alias Map — src/producer-aliases.js
// Format: "customer input variant": "canonical name as stored in DB"
// All keys lowercase. Applied before tokenising in parseMatchTokens.
//
// TO ADD A NEW ALIAS:
// 1. Search main app to confirm exact DB name
// 2. Add: "variant": "canonical name",
// 3. Save — Vite hot-reloads automatically
//
const PRODUCER_ALIASES = {

  // ── Australian — Apostrophe variants ────────────────────────────
  "tyrells": "tyrrell's",
  "tyrrells": "tyrrell's",
  "hardys": "hardy's",
  "henschkes": "henschke's",
  "bests": "best's",
  "mcwilliams": "mcwilliam's",
  "mcwilliam": "mcwilliam's",
  "jacobs": "jacob's",
  "zontes": "zonte's",
  "mcleans": "mclean's",
  "mccleans": "mclean's",
  "lehmanns": "lehmann's",
  "reynells": "reynell's",
  "wendourees": "wendouree's",
  "seppelts": "seppelt's",
  "lindemans": "lindeman's",
  "hardysregency": "hardy's",
  "wollaston": "wollaston's",
  "jeansons": "jeanson's",
  "draytons": "drayton's",
  "drayton": "drayton's",
  "petersons": "peterson's",
  "petersonshouse": "peterson's house",
  "hamiltons": "hamilton's",
  "hardyshollick": "hardy's hollick",
  "pikesplace": "pike's",
  "pikes": "pike's",
  "stjohns": "st john's",
  "standrews": "st andrew's",
  "stanthonys": "st anthony's",
  "oliverstarke": "oliver's taranga",
  "oliverstaranga": "oliver's taranga",
  "bekkers": "bekker's",
  "geoffs": "geoff's",
  "lindemanestate": "lindeman's",
  "lindemansestate": "lindeman's",
  "rawsons": "rawson's retreat",
  "rawsonsretreat": "rawson's retreat",
  "stanne": "st anne's",
  "stmary": "st mary's",
  "darenbergs": "d'arenberg",
  "pikeswinery": "pike's",
  "darenberg": "d'arenberg",

  // ── Australian — Run-together names ─────────────────────────────
  "debortoliis": "de bortoli",
  "debortolis": "de bortoli",
  "mounthorrocks": "mount horrocks",
  "taylors": "taylors wines",
  "stephenblocks": "stephen block",
  "twohands": "two hands",
  "clarendonhills": "clarendon hills",
  "powellandsons": "powell and son",
  "powellsons": "powell and son",
  "peterlehmanns": "peter lehmann",
  "wolfblassprecious": "wolf blass",
  "woodstockwines": "woodstock winery",
  "curlewis": "curlewis winery",
  "zemas": "zema estate",
  "katnooks": "katnook estate",
  "rosemounts": "rosemount estate",
  "hbharveys": "h.b. harvey",
  "franklandestates": "frankland estate",
  "franklands": "frankland estate",
  "howardparks": "howard park",
  "cullens": "cullen wines",
  "leeuwins": "leeuwin estate",
  "amberleys": "amberley estate",
  "gallows": "gallows wine co",
  "wynns": "wynns coonawarra",
  "foxcreeks": "fox creek",
  "jimbarrys": "jim barry",
  "jimbarries": "jim barry",
  "annie's": "annies lane",
  "timadams": "tim adams",
  "timadamses": "tim adams",
  "mitchells": "mitchell wines",
  "stanleybros": "stanley brothers",
  "stanleybrothers": "stanley brothers",
  "turkeyflats": "turkey flat",
  "torbrecks": "torbreck vintners",
  "torbrekvintners": "torbreck vintners",
  "wyndhamsestate": "wyndham estate",
  "debortolie": "de bortoli",
  "debortoli": "de bortoli",
  "hamiltonsewell": "hamilton ewell",
  "wolfblass": "wolf blass",
  "yellowglen": "yellow glen",
  "wirrawirra": "wirra wirra",
  "tempustwo": "tempus two",
  "mclarenvale": "mclaren vale",
  "mountadam": "mount adam",
  "mountmary": "mount mary",
  "mountpleasant": "mount pleasant",
  "mountlangi": "mount langi",
  "mountlangighiran": "mount langi ghiran",
  "mountbenson": "mount benson",
  "mountgambier": "mount gambier",
  "mountbarker": "mount barker",
  "peterle": "peter lehmann",
  "peterlehmann": "peter lehmann",
  "wolfblassgold": "wolf blass",
  "wolfblasseagle": "wolf blass",
  "standre": "st andre",
  "samueltilbrook": "samuel tilbrook",
  "scarpantoni": "scarpantoni estate",
  "geoffmerrill": "geoff merrill",
  "richardhamilton": "richard hamilton",
  "rhanilton": "richard hamilton",
  "woodstock": "woodstock winery",
  "hollick": "hollick wines",
  "leconfield": "leconfield wines",
  "majella": "majella wines",
  "zema": "zema estate",
  "katnook": "katnook estate",
  "wynndham": "wyndham estate",
  "wyndhamestate": "wyndham estate",
  "rosemount": "rosemount estate",
  "jackaroo": "jackaroo wines",
  "yellowtail": "yellow tail",
  "casella": "casella wines",
  "[yellowtail]": "yellow tail",
  "sthallett": "st hallett",
  "sthugo": "st hugo",
  "stpedri": "st pedri",
  "sthelena": "st helena",
  "stbernadette": "st bernadette",
  "stgeorge": "st george",
  "rwine": "r wine",
  "efbest": "e & f best",
  "yarrayang": "yarra yering",
  "tarrahill": "terra hill",
  "paringa": "paringa estate",
  "howardpk": "howard park",
  "vassefelix": "vasse felix",
  "cullen": "cullen wines",
  "leeuwin": "leeuwin estate",
  "mosswood": "moss wood",
  "mosswoo": "moss wood",
  "capementelle": "cape mentelle",
  "amberley": "amberley estate",
  "wirra": "wirra wirra",
    "foxcreek": "fox creek",
  "jimbarry": "jim barry",
  "annalise": "annies lane",
  "annieslane": "annies lane",
  "mitchell": "mitchell wines",
  "turkeyflat": "turkey flat",
  "torbreck": "torbreck vintners",

  // ── Australian — Misspellings ───────────────────────────────────
  "hoffmans": "hoffmann",
  "hentschkes": "henschke",
  "lindermans": "lindeman's",
  "linderman": "lindeman's",
  "devilslair": "devil's lair",
  "devillair": "devil's lair",
  "yarrayering": "yarra yering",
  "yarryering": "yarra yering",
  "parringa": "paringa estate",
  "capementell": "cape mentelle",
  "kilianoon": "kilikanoon",
  "longhorne": "langhorne",
  "longhorn": "langhorne",
  "tununda": "tanunda",
  "hoffman": "hoffmann",
  "mauolo": "maiolo",
  "hentschke": "henschke",
  "henscke": "henschke",
  "henshcke": "henschke",
  "henshke": "henschke",
  "brockenwood": "brokenwood",
  "tiltarni": "taltarni",
  "taltarnie": "taltarni",
  "tahblik": "tahbilk",
  "mitchellton": "mitchelton",
  "moorduc": "moorooduc",
  "mooroduc": "moorooduc",
  "moordooduc": "moorooduc",
  "tolpudle": "tolpuddle",
  "tolpuddel": "tolpuddle",
  "dalwhinie": "dalwhinnie",
  "dalwhinney": "dalwhinnie",
  "picardi": "picardy",
  "sittela": "sittella",
  "xanadoo": "xanadu",

  // ── Australian — Shortened/alternate names ──────────────────────
  "tullochs": "tulloch",
  "brokenwoods": "brokenwood",
  "mcguigans": "mcguigan",
  "rothburys": "rothbury",
  "arrowfields": "arrowfield",
  "allanvales": "allanvale",
  "reynellas": "reynella",
  "yalumbas": "yalumba",
  "grossets": "grosset",
  "jeffreys": "jeffrey",
  "leasinghams": "leasingham",
  "kilikanoons": "kilikanoon",
  "mitchs": "mitchelton",
  "taras": "tara",
  "langmeils": "langmeil",
  "rokstons": "rokston",
  "pattersons": "patterson",
  "hollicks": "hollick",
  "leconfields": "leconfield",
  "majellas": "majella",
  "pendfolds": "penfolds",
  "penfoldes": "penfolds",
  "rockfords": "rockford",
  "kooyongs": "kooyong",
  "pooleys": "pooley",
  "cherubinos": "cherubino",
  "xanadus": "xanadu",
  "thomas hardys": "thomas hardy",
  "wollass": "wollastons",
  "batesman": "batesmann",
  "penfold": "penfolds",
  "giaconder": "giaconda",
  "kooyonga": "kooyong",
  "moorila": "moorilla",
  "penfolds bin": "penfolds",
  "scrapantoni": "scarpantoni",
  "riesling freak": "rieslingfreak",
  "penfolds grange": "penfolds",
  "saint hugo": "st hugo",
  "saint hallett": "st hallett",

  // ── French — Burgundy ───────────────────────────────────────────
  "drc": "domaine de la romanee-conti",
  "romaneeconti": "domaine de la romanee-conti",
  "romanee conti": "domaine de la romanee-conti",
  "domaineromaneeconti": "domaine de la romanee-conti",
  "leroy": "domaine leroy",
  "leroys": "domaine leroy",
  "rousseau": "domaine armand rousseau",
  "armand rousseau": "domaine armand rousseau",
  "rousseaus": "domaine armand rousseau",
  "dujac": "domaine dujac",
  "dujacs": "domaine dujac",
  "ponsot": "domaine ponsot",
  "ponsots": "domaine ponsot",
  "mugnier": "domaine mugnier",
  "mugniers": "domaine mugnier",
  "jf mugnier": "domaine mugnier",
  "comte vogue": "domaine comte de vogue",
  "vogüé": "domaine comte de vogue",
  "vogue": "domaine comte de vogue",
  "ramonet": "domaine ramonet",
  "ramonets": "domaine ramonet",
  "lafon": "domaine des comtes lafon",
  "comtes lafon": "domaine des comtes lafon",
  "leflaive": "domaine leflaive",
  "leflaives": "domaine leflaive",
  "sauzet": "domaine etienne sauzet",
  "coche dury": "domaine coche-dury",
  "coche-dury": "domaine coche-dury",
  "cochederuy": "domaine coche-dury",
  "drouhin": "joseph drouhin",
  "jadot": "louis jadot",
  "louis jadots": "louis jadot",
  "bouchard": "bouchard pere et fils",
  "bouchardpere": "bouchard pere et fils",
  "faiveley": "domaine faiveley",
  "faivleys": "domaine faiveley",
  "grivot": "domaine jean grivot",
  "jean grivot": "domaine jean grivot",
  "meo camuzet": "domaine meo-camuzet",
  "meocamuzet": "domaine meo-camuzet",
  "meo-camuzet": "domaine meo-camuzet",
  "trapet": "domaine trapet",
  "trapets": "domaine trapet",
  "bachelet": "domaine bachelet",
  "burguet": "domaine alain burguet",
  "mortet": "domaine denis mortet",
  "denis mortet": "domaine denis mortet",
  "rossignol trapet": "domaine rossignol-trapet",
  "rossignoltrapet": "domaine rossignol-trapet",
  "fourrier": "domaine fourrier",
  "fourniers": "domaine fourrier",
  "tollot beaut": "domaine tollot-beaut",
  "tollotbeaut": "domaine tollot-beaut",
  "chandon de briailles": "domaine chandon de briailles",
  "chandonbriailles": "domaine chandon de briailles",
  "simon bize": "domaine simon bize",
  "simonbize": "domaine simon bize",
  "roulot": "domaine roulot",
  "roulots": "domaine roulot",
  "jobard": "domaine francois jobard",
  "bonneau martray": "domaine bonneau du martray",
  "bonneaudumartray": "domaine bonneau du martray",

  // ── French — Rhône ──────────────────────────────────────────────
  "guigal": "e. guigal",
  "eguigal": "e. guigal",
  "chapoutier": "m. chapoutier",
  "mchapoutier": "m. chapoutier",
  "jaboulet": "paul jaboulet aine",
  "pauljaboulet": "paul jaboulet aine",
  "jamet": "domaine jamet",
  "jamets": "domaine jamet",
  "chave": "jean-louis chave",
  "jlchave": "jean-louis chave",
  "jean louis chave": "jean-louis chave",
  "closdespapes": "clos des papes",
  "rayas": "chateau rayas",
  "chateaurayas": "chateau rayas",
  "beaucastel": "chateau de beaucastel",
  "debeaucastel": "chateau de beaucastel",
  "vieux telegraphe": "domaine du vieux telegraphe",
  "vieuxtelgraphe": "domaine du vieux telegraphe",
  "vieuxtelégraphe": "domaine du vieux telegraphe",

  // ── French — Bordeaux ───────────────────────────────────────────
  "lepin": "le pin",
  "ausone": "chateau ausone",
  "chausone": "chateau ausone",
  "cheval blanc": "chateau cheval blanc",
  "chevalblanc": "chateau cheval blanc",
  "lafite": "chateau lafite rothschild",
  "lafitrothschild": "chateau lafite rothschild",
  "lafite rothschild": "chateau lafite rothschild",
  "mouton": "chateau mouton rothschild",
  "mouton rothschild": "chateau mouton rothschild",
  "moutonrothschild": "chateau mouton rothschild",
  "latour": "chateau latour",
  "chlatour": "chateau latour",
  "margaux": "chateau margaux",
  "chmargaux": "chateau margaux",
  "haut brion": "chateau haut-brion",
  "hautbrion": "chateau haut-brion",
  "haut-brion": "chateau haut-brion",
  "angelus": "chateau angelus",
  "chateauangelus": "chateau angelus",
  "pavie": "chateau pavie",
  "pichon baron": "chateau pichon-longueville baron",
  "pichon lalande": "chateau pichon-longueville comtesse de lalande",
  "pichonlalande": "chateau pichon-longueville comtesse de lalande",
  "pichonbaron": "chateau pichon-longueville baron",
  "ducru": "chateau ducru-beaucaillou",
  "ducrubeaucaillou": "chateau ducru-beaucaillou",
  "leoville lascases": "chateau leoville-las-cases",
  "leovillelascases": "chateau leoville-las-cases",
  "leoville barton": "chateau leoville barton",
  "leovillebarton": "chateau leoville barton",
  "palmer": "chateau palmer",
  "chpalmer": "chateau palmer",
  "lynch bages": "chateau lynch-bages",
  "lynchbages": "chateau lynch-bages",
  "montrose": "chateau montrose",
  "chmont rose": "chateau montrose",
  "calon segur": "chateau calon-segur",
  "calonsegur": "chateau calon-segur",
  "cos destournel": "chateau cos d'estournel",
  "cosdestournel": "chateau cos d'estournel",
  "cos d'estournel": "chateau cos d'estournel",
  "petite mouton": "petit mouton de mouton rothschild",
  "carruades": "carruades de lafite",
  "carruadeslafite": "carruades de lafite",
  "pavillon rouge": "pavillon rouge du chateau margaux",
  "pavillonrouge": "pavillon rouge du chateau margaux",

  // ── French — Champagne ──────────────────────────────────────────
  "domperignon": "dom perignon",
  "krugs": "krug",
  "cristal": "louis roederer cristal",
  "roederer": "louis roederer",
  "louisroederer": "louis roederer",
  "salonchampagne": "salon",
  "bollingers": "bollinger",
  "polroger": "pol roger",
  "taittingers": "taittinger",
  "veuveclicquot": "veuve clicquot",
  "perrier jouet": "perrier-jouet",
  "perrierjouet": "perrier-jouet",

  // ── Italian — Piedmont ──────────────────────────────────────────
  "gajas": "gaja",
  "giacomoconterno": "giacomo conterno",
  "g conterno": "giacomo conterno",
  "bartolomascarello": "bartolo mascarello",
  "giuseppemascarello": "giuseppe mascarello",
    "brunogiacosa": "bruno giacosa",
    "aldoconterno": "aldo conterno",
  "elioaltare": "elio altare",
      "viet ti": "vietti",
  "produttori": "produttori del barbaresco",
  "produttoridel": "produttori del barbaresco",
  "marchesidibarolo": "marchesi di barolo",
  "prunottos": "prunotto",
          "paoloscavino": "paolo scavino",

  // ── Italian — Tuscany ───────────────────────────────────────────
  "sassicaia": "tenuta san guido sassicaia",
  "san guido": "tenuta san guido",
  "tenutagiuido": "tenuta san guido",
  "ornellaia": "tenuta dell ornellaia",
  "tenuta ornellaia": "tenuta dell ornellaia",
  "massetos": "masseto",
  "solaia": "antinori solaia",
  "tignanello": "antinori tignanello",
  "antinoris": "antinori",
  "biondi santi": "biondi-santi",
  "biondisanti": "biondi-santi",
    "casanova neri": "casanova di neri",
  "casanovadineri": "casanova di neri",
  "col d orcia": "col d'orcia",
  "coldorcia": "col d'orcia",
  "poggiantico": "poggio antico",
  "pertimali": "pertimali livio sassetti",
  "salicutti": "podere salicutti",
  "ciacci piccolomini": "ciacci piccolomini d'aragona",
  "lemacchiole": "le macchiole",
  "guadoaltasso": "guado al tasso",

  // ── American — California ───────────────────────────────────────
  "screaминgeagle": "screaming eagle",
  "screamineagle": "screaming eagle",
  "harlan": "harlan estate",
  "harlanestate": "harlan estate",
    "bondestates": "bond estates",
  "opusone": "opus one",
    "dalla valle": "dalla valle vineyards",
  "dallavalle": "dalla valle vineyards",
  "bryant family": "bryant family vineyard",
  "bryantfamily": "bryant family vineyard",
  "colgin": "colgin cellars",
  "colgins": "colgin cellars",
  "grace family": "grace family vineyards",
  "gracefamily": "grace family vineyards",
  "araujo": "araujo estate",
  "araujos": "araujo estate",
  "dominus": "dominus estate",
  "dominusestate": "dominus estate",
  "insignia": "joseph phelps insignia",
  "josephphelps": "joseph phelps",
  "caymus": "caymus vineyards",
  "caymuss": "caymus vineyards",
  "stag's leap": "stag's leap wine cellars",
  "stagsleap": "stag's leap wine cellars",
  "staglin": "staglin family vineyard",
  "staglin family": "staglin family vineyard",
  "beringer": "beringer vineyards",
  "beringers": "beringer vineyards",
    "ridge montebello": "ridge vineyards monte bello",
  "ridgemontebello": "ridge vineyards monte bello",
  "heitz": "heitz cellar",
  "heitzcellar": "heitz cellar",
  "marthas vineyard": "heitz cellar martha's vineyard",
  "spottswoode": "spottswoode estate",
  "spotswoodeestate": "spottswoode estate",
  "dunn": "dunn vineyards",
  "dunns": "dunn vineyards",
  "philip togni": "philip togni vineyard",
  "philiptogni": "philip togni vineyard",
    "abreu": "abreu vineyard",
  "abreus": "abreu vineyard",
  "blankiet": "blankiet estate",
  "kongsgaard": "kongsgaard winery",
  "kistler": "kistler vineyards",
  "kistlers": "kistler vineyards",
  "marcassins": "marcassin",
  "peter michael": "peter michael winery",
  "petermichael": "peter michael winery",
  "aubert": "aubert wines",
  "auberts": "aubert wines",
  "ramey": "ramey wine cellars",
  "rameys": "ramey wine cellars",
  "sea smoke": "sea smoke cellars",
  "seasmoke": "sea smoke cellars",
  "brewer clifton": "brewer-clifton",
  "brewerclifton": "brewer-clifton",
  "sandhi": "sandhi wines",
  "sinequanon": "sine qua non",
    "albans": "alban vineyards",
  "saxum": "saxum vineyards",
  "saxums": "saxum vineyards",
          "tablas creek": "tablas creek vineyard",
  "tablascreek": "tablas creek vineyard",

  // ── American — Oregon/Washington ────────────────────────────────
  "adelsheim": "adelsheim vineyard",
  "domaine drouhin": "domaine drouhin oregon",
  "domainedrouhin": "domaine drouhin oregon",
  "elk cove": "elk cove vineyards",
  "elkcove": "elk cove vineyards",
  "eyrie": "the eyrie vineyards",
  "eyrievineyards": "the eyrie vineyards",
  "ponzi": "ponzi vineyards",
  "ponzis": "ponzi vineyards",
  "rexhill": "rex hill",
  "beauxfreres": "beaux freres",
  "brickhouse": "brick house",
  "cayuse": "cayuse vineyards",
  "cayuses": "cayuse vineyards",
  "quilcedacreek": "quilceda creek",
  "leonetti": "leonetti cellar",
  "leonettis": "leonetti cellar",
  "andrew will": "andrew will winery",
  "andrewwill": "andrew will winery",
  "delille": "delille cellars",
  "de lille": "delille cellars",

  // ── Other ─────────────────────────────────────────────────────────────────
  "stantons": "stanton",
  "stoniers": "stonier",

};

export default PRODUCER_ALIASES;